repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements

- repo: https://github.com/psf/black
  rev: "22.12.0" # Keep in sync with blacken-docs
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: "blacken-docs"
    additional_dependencies:
    - black==22.12.0 # keep in sync with black hook

