version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: Documentation/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: Documentation/requirements.txt
