function [pose] = getPose(autoscoper_socket,volume, frame)
%GETPOSE Summary of this function goes here
%   Detailed explanation goes here
fwrite(autoscoper_socket,[6 typecast(int32(volume),'uint8') typecast(int32(frame),'uint8')]);
while autoscoper_socket.BytesAvailable == 0
    pause(1)
end
data = fread(autoscoper_socket, autoscoper_socket.BytesAvailable);

pose = [...
    typecast(uint8(data(2:9)),'double') ...
    typecast(uint8(data(10:17)),'double') ...
    typecast(uint8(data(18:25)),'double') ...
    typecast(uint8(data(26:33)),'double') ...
    typecast(uint8(data(34:41)),'double') ...
    typecast(uint8(data(42:49)),'double') ]

end

